services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_DB=${SERVICE_DATABASE_POSTGRES}
    ports:
      - "${SERVICE_PORT_POSTGRES}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SERVICE_USER_POSTGRES} -d ${SERVICE_DATABASE_POSTGRES}" ]
      interval: 10s
      timeout: 5s
      retries: 5